title: Typescript and Sass Webpack Boilerplate
description: A simple webpack boilerplate for front end projects using Typescript/Sass
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
